#SELECT DISTINCT(CITY) FROM STATION WHERE CITY REGEXP '^[^aeiou]' OR CITY REGEXP '[^aeiou]$';
DROP PROCEDURE IF EXISTS simple_proc;
DELIMITER //
CREATE PROCEDURE simple_proc()
BEGIN
	DECLARE x INT DEFAULT 0;
	DECLARE y INT DEFAULT 0;
	DECLARE z INT DEFAULT 0;
	DECLARE cx INT DEFAULT 0;
	DECLARE rows INT DEFAULT 0;
	DECLARE curs CURSOR FOR SELECT A,B,C FROM TRIANGLE;
	SELECT COUNT(*) INTO rows FROM TRIANGLE;
	OPEN curs;
	x_loop: LOOP
		SET cx = cx + 1;
		FETCH curs INTO x, y, z;
		SELECT CONCAT('X : Y : Z = ', x, ':', y, ':', z);
		IF x > y THEN
			SELECT CONCAT('X BIGGER: ', x);
		ELSEIF y > x THEN
			SELECT CONCAT('Y BIGGER: ', y);
		END IF;
		IF cx >= rows THEN LEAVE x_loop; END IF;
	END LOOP x_loop;
	CLOSE curs;
	SELECT * FROM TRIANGLE;
END //
DELIMITER ;

CALL simple_proc();
/*
DELIMITER //
CREATE PROCEDURE simple_proc()
BEGIN
	SELECT * FROM TRIANGLE;
END //
DELIMITER ;

CALL simple_proc();
*/